apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: anpr
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: "hello@123"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: postgres-storage
          emptyDir: {}
        - name: initdb
          configMap:
            name: postgres-initdb-config
